### PR TITLE
expose a function to create the database schema programmatically

### PR DESCRIPTION
**Pull request by erizocosmico**
First part of https://github.com/src-d/borges/issues/21

### CODE REVIEW

**Comment by ajnavarro** [comment]
I think you need to regenerate kallax.go files.

**Comment by erizocosmico** [comment]
It's because of the check that ensures that the schema is generated with bindata. Idk, why they don't match, it should not have any metadata.

**Comment by erizocosmico** [comment]
Fixed @ajnavarro

**Comment by ajnavarro** [comment]
@erizocosmico sorry, rebase please.

**Comment by erizocosmico** [comment]
Done @ajnavarro

**Comment by erizocosmico** [comment]
Yes! Good idea! The CI ensures the models and schema are generated but there should definitely be a note in the readme explaining how it's done
On Thu, 10 Aug 2017 at 07:32, Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:

Really nice tooling!

May be later we could add a small reminder in README about make generate-models and checking in bindata in case of schema changes.

**Pull request merged**
