### PR TITLE
Use new sivaFS constructor and add integration tests

### PR DESCRIPTION
**Pull request by ajnavarro**

### CODE REVIEW

**Comment by ajnavarro** [comment]
depends on https://github.com/src-d/go-billy-siva/pull/9

**Comment by bzz** [comment]
Looks good to me! 👍 for integration test \w real repository

Travis CI fails with `model/mention.go:5: running "kallax": exec: "kallax": executable file not found in $PATH`, @ajnavarro do you think it should be debugged outside of this pr?

One useful approach here can be 
 - adding `echo $PATH` and `ls -la /path/to/kallax` to

**Comment by ajnavarro** [comment]
@smola we will need a new go-billy-siva release for this.

**Comment by ajnavarro** [comment]
Pending: https://github.com/src-d/core-retrieval/pull/18

**Pull request merged**
