### PR TITLE
Update go-billy dependency to v4

### PR DESCRIPTION
**Pull request by jfontan**
Requires merging this PR https://github.com/src-d/go-billy-siva/pull/16

### CODE REVIEW

**Comment by jfontan** [comment]
`go-git` v4 is still not released and a branch called `v4` exists in the repository (this is selected when using `gopkg.in/src-d/go-git.v4`). That branch is not up to date and does not contain the fix for HTTP transport (https://github.com/src-d/go-git/pull/657). It also points to `go-siva.v3`. This causes a problem testing the package as we expect to have `go-siva.v4`.

Possible solutions:

* Download master go-git in vendor directory before doing tests
* Update or delete `v4` branch form `go-git` repo to master
* Use glide also for testing `core-retrieval`
* Backport `go-git` fix to v3 and continue using that version

**Comment by erizocosmico** [comment]
We could just delete the `v4` branch. Nothing _should_ break

**Comment by jfontan** [comment]
I've tested deleting the branch in my clone and it does not work as there is no proper release tag. :(

http://gopkg.in/jfontan/go-git.v4

**Comment by erizocosmico** [comment]
but we have several `-rcX` in go-git, right?

**Comment by jfontan** [comment]
That's right, there are several release candidates but those are not picked by gopkg.in service.

I've uploaded the branch to this repo. I'm fixing the version to the commit hash in `borges` until `go-git` version 4 is released.

**Comment by erizocosmico** [comment]
Ah, right. Then pushing stuff to v4 it is, I guess

**Pull request merged**
